/* AUTOGENERATED by _gen_ui.py - edit the generator, not this file. */
(function () {
  var Q = window.QwenPaw;
  if (!Q || !Q.host || !Q.host.React || !Q.registerRoutes) return;
  var React = Q.host.React;
  var antd = Q.host.antd;
  var h = React.createElement;
  var Fragment = React.Fragment;
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useRef = React.useRef;
  var APP = "/zhiyun-people-studio";
  var ID = "zhiyun-people-studio";

  var T = {
    bg: "#f4f6f9", panel: "#ffffff", inset: "#f8fafc", border: "#e3e8ef",
    borderStrong: "#d3dae3", text: "#1f2933", sub: "#5b6472", faint: "#98a2b3",
    primary: "#b45309", primaryDark: "#92400e", primarySoft: "#fff7ed",
    green: "#16a34a", amber: "#d97706", red: "#dc2626", violet: "#6d28d9",
    cyan: "#0891b2", radius: 8, radiusLg: 10,
    shadow: "0 1px 2px rgba(16,24,40,0.04), 0 2px 6px rgba(16,24,40,0.06)"
  };
  var APP_TITLE = "智能人力与协同中心";
  var APP_SUBTITLE = "权限建议、全员通讯录、审批路径、员工关怀与人力分析";
  var CSS_ID = "zy-" + ID + "-css";
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var style = document.createElement("style");
    style.id = CSS_ID;
    style.textContent = [
      ".zy-app,.zy-app *{box-sizing:border-box;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Microsoft YaHei',sans-serif;}",
      ".zy-app{background:" + T.bg + ";min-height:100%;}",
      ".zy-topbar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:14px;padding:14px 104px 14px 24px;background:rgba(255,255,255,0.92);backdrop-filter:blur(8px);border-bottom:1px solid " + T.border + ";}",
      ".zy-monogram{width:38px;height:38px;border-radius:10px;background:" + T.primary + ";color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:16px;flex:0 0 auto;box-shadow:" + T.shadow + ";}",
      ".zy-topbar-title{font-weight:650;font-size:16px;color:" + T.text + ";line-height:1.2;}",
      ".zy-topbar-sub{font-size:12px;color:" + T.sub + ";margin-top:2px;}",
      ".zy-body{display:flex;gap:20px;max-width:1360px;margin:0 auto;padding:20px 24px 40px;}",
      ".zy-rail{width:224px;flex:0 0 auto;background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:" + T.radiusLg + "px;padding:10px;height:fit-content;position:sticky;top:84px;}",
      ".zy-rail-label{font-size:11px;color:" + T.faint + ";letter-spacing:.04em;margin:4px 8px 8px;font-weight:600;}",
      ".zy-nav-item{display:flex;align-items:flex-start;gap:10px;padding:11px;border-radius:9px;cursor:pointer;border:1px solid transparent;transition:all .18s ease;}",
      ".zy-nav-item:hover{background:" + T.inset + ";}",
      ".zy-nav-item.zy-active{background:" + T.primarySoft + ";border-color:#c7dcff;}",
      ".zy-nav-ico{width:30px;height:30px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:15px;background:" + T.inset + ";border:1px solid " + T.border + ";flex:0 0 auto;}",
      ".zy-nav-item.zy-active .zy-nav-ico{background:" + T.primary + ";color:#fff;border-color:" + T.primary + ";}",
      ".zy-nav-name{font-size:13px;font-weight:600;color:" + T.text + ";line-height:1.3;}",
      ".zy-nav-desc{font-size:11px;color:" + T.sub + ";margin-top:3px;line-height:1.4;}",
      ".zy-main{flex:1 1 auto;min-width:0;}",
      ".zy-panel{background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:" + T.radiusLg + "px;box-shadow:" + T.shadow + ";}",
      ".zy-panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid " + T.border + ";}",
      ".zy-panel-title{font-size:14px;font-weight:650;color:" + T.text + ";}",
      ".zy-panel-sub{font-size:12px;color:" + T.sub + ";margin-top:3px;}",
      ".zy-panel-body{padding:16px 18px;}",
      ".zy-cols{display:grid;grid-template-columns:minmax(360px,0.92fr) minmax(0,1.08fr);gap:16px;align-items:start;}",
      ".zy-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;}",
      ".zy-define h4{font-size:12px;color:" + T.faint + ";font-weight:600;margin:0 0 8px;}",
      ".zy-define p{font-size:12px;color:" + T.sub + ";line-height:1.55;margin:0;}",
      ".zy-answer{white-space:pre-wrap;font-size:13px;color:" + T.text + ";line-height:1.7;background:" + T.inset + ";border:1px solid " + T.border + ";border-radius:9px;padding:14px 16px;}",
      ".zy-tagline{font-size:12px;color:" + T.sub + ";line-height:1.5;}",
      ".zy-fade{animation:zyFade .28s ease both;}",
      "@keyframes zyFade{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}",
      ".zy-mask{position:fixed;inset:0;background:rgba(15,23,42,0.32);z-index:1000;animation:zyFade .18s ease both;}",
      ".zy-dock{position:fixed;top:0;right:0;bottom:0;width:min(420px,92vw);background:" + T.panel + ";border-left:1px solid " + T.border + ";box-shadow:-10px 0 30px rgba(16,24,40,0.16);z-index:1001;display:flex;flex-direction:column;animation:zyFade .22s ease both;}",
      ".zy-chat{display:flex;flex-direction:column;height:100%;}",
      ".zy-chat-head{padding:14px 16px;background:" + T.panel + ";border-bottom:1px solid " + T.border + ";}",
      ".zy-chat-list{flex:1 1 auto;overflow:auto;padding:16px;}",
      ".zy-msg{display:flex;flex-direction:column;gap:6px;margin-bottom:14px;}",
      ".zy-msg-bubble{max-width:92%;padding:10px 12px;border-radius:11px;font-size:12.5px;line-height:1.6;box-shadow:" + T.shadow + ";}",
      ".zy-msg-user{align-items:flex-end;}",
      ".zy-msg-user .zy-msg-bubble{background:" + T.primary + ";color:#fff;border-bottom-right-radius:3px;}",
      ".zy-msg-bot{align-items:flex-start;}",
      ".zy-msg-bot .zy-msg-bubble{background:" + T.panel + ";border:1px solid " + T.border + ";border-bottom-left-radius:3px;color:" + T.text + ";}",
      ".zy-msg-card{max-width:92%;background:" + T.panel + ";border:1px solid " + T.border + ";border-radius:11px;padding:12px 14px;box-shadow:" + T.shadow + ";}",
      ".zy-chat-input{padding:12px 14px;background:" + T.panel + ";border-top:1px solid " + T.border + ";}",
      ".zy-chips{display:flex;flex-wrap:wrap;gap:8px;}",
      ".zy-chip{border:1px solid " + T.border + ";background:" + T.panel + ";border-radius:999px;padding:6px 12px;font-size:12px;color:" + T.sub + ";cursor:pointer;transition:all .16s ease;user-select:none;}",
      ".zy-chip:hover{border-color:" + T.primary + ";color:" + T.primary + ";background:" + T.primarySoft + ";}",
      ".zy-status-dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:6px;}",
      ".zy-run{transition:transform .16s ease;}",
      ".zy-run:hover{transform:translateY(-1px);}",
      ".zy-hint{font-size:12px;color:" + T.sub + ";line-height:1.6;background:" + T.inset + ";border:1px dashed " + T.border + ";border-radius:9px;padding:10px 12px;}",
      ".zy-cellgap th,.zy-cellgap td{padding:9px 8px!important;vertical-align:top;}",
      "@media(max-width:980px){.zy-body{flex-direction:column;padding:16px;}.zy-rail{width:100%;position:static;top:auto;}.zy-cols{grid-template-columns:1fr;}}"
    ].join("\n");
    document.head.appendChild(style);
  }
  ensureCss();

  function request(path, body) {
    return Q.host.fetch(path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body)
    }).then(function (response) {
      return response.json().then(function (data) {
        if (!response.ok) throw new Error(data.detail || ("HTTP " + response.status));
        return data;
      });
    });
  }
  function getJson(path) {
    return Q.host.fetch(path).then(function (response) { return response.json(); });
  }
  function pushAgentContext(ctx) {
    if (Q.setAgentContext) Q.setAgentContext(ctx);
    else window.dispatchEvent(new CustomEvent("qwenpaw:agent-context", { detail: ctx }));
  }
  function fmt(value) { return value == null || value === "" ? "—" : String(value); }
  function isBlank(value) { return value == null || value === "" || (Array.isArray(value) && !value.length); }
  function clone(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
  function sampleFor(mod) { return mod.sample != null ? mod.sample : mod.example; }
  var IMPORT_MAX_ROWS = 500;
  var IMPORT_ENDPOINT = "/zhiyun-data-core/parse";
  function normHeader(value) { return String(value == null ? "" : value).trim().toLowerCase().replace(/[\s（）()【】\[\]]/g, ""); }
  function headerCandidates(col) {
    var seen = {}, out = [];
    [col.label, col.key].concat(col.aliases || []).forEach(function (item) {
      var norm = normHeader(item);
      if (norm && !seen[norm]) { seen[norm] = true; out.push(norm); }
    });
    return out;
  }
  function buildHeaderIndex(headers, cols) {
    var used = {}, index = {};
    (headers || []).forEach(function (header, position) {
      var norm = normHeader(header);
      if (!norm) return;
      cols.forEach(function (col) {
        if (index[col.key] !== undefined) return;
        if (headerCandidates(col).indexOf(norm) !== -1 && !used[norm]) { used[norm] = true; index[col.key] = position; }
      });
    });
    return index;
  }
  function coerceCell(raw, col) {
    if (raw == null) return col.type === "tags" ? [] : "";
    if (col.type === "number") { var num = Number(raw); return raw === "" || num !== num ? "" : num; }
    if (col.type === "tags") {
      if (Array.isArray(raw)) return raw;
      return String(raw).split(/[，,;；、]/).map(function (part) { return part.trim(); }).filter(Boolean);
    }
    return String(raw);
  }
  function rowsFromParsed(parsed, cols) {
    var headers = parsed.headers || [];
    var index = buildHeaderIndex(headers, cols);
    var matched = Object.keys(index);
    var rows = [];
    if (matched.length) {
      (parsed.rows || []).forEach(function (line) {
        var asDict = line && typeof line === "object" && !Array.isArray(line);
        var row = {}, hasValue = false;
        cols.forEach(function (col) {
          var position = index[col.key];
          var raw = null;
          if (position !== undefined) {
            // /parse 的行可能是“按表头的字典”或“按下标的数组”，两种形态都兼容
            raw = asDict ? line[headers[position]] : line[position];
          }
          row[col.key] = coerceCell(raw, col);
          var v = row[col.key];
          if (v !== "" && !(Array.isArray(v) && !v.length)) hasValue = true;
        });
        if (hasValue) rows.push(row);
      });
    }
    return { rows: rows, matched: matched };
  }
  var __ridSeq = 10000;
  function nextRid() { __ridSeq += 1; return "r" + __ridSeq; }
  function withRid(rows) {
    return (rows || []).map(function (r) {
      if (r && r.__rid) return r;
      var copy = Object.assign({}, r || {});
      copy.__rid = nextRid();
      return copy;
    });
  }
  function stripRid(value) {
    if (Array.isArray(value)) return value.map(stripRid);
    if (value && typeof value === "object") {
      var out = {};
      Object.keys(value).forEach(function (k) { if (k !== "__rid") out[k] = stripRid(value[k]); });
      return out;
    }
    return value;
  }
  function statusTone(status) {
    if (status === "accepted") return { color: "green", text: "已接受" };
    if (status === "rejected") return { color: "red", text: "已驳回" };
    return { color: "orange", text: "待审阅" };
  }
  function statusColor(status) {
    if (status === "紧急补货") return "red";
    if (status === "建议补货") return "orange";
    if (status === "库存充足") return "green";
    if (status === "达标") return "green";
    if (status === "接近") return "orange";
    if (status === "落后") return "red";
    return "default";
  }

  function RefreshIcon() {
    return h("span", { style: { fontSize: 13 } }, "⟳");
  }
  function SparkIcon() { return h("span", { style: { fontSize: 13 } }, "✦"); }
  function AgentIcon() { return h("span", { style: { fontSize: 13 } }, "✦"); }

  function AppHeader(props) {
    return h("div", { className: "zy-topbar" },
      h("div", { className: "zy-monogram" }, "人力"),
      h("div", { style: { flex: 1, minWidth: 0 } },
        h("div", { className: "zy-topbar-title" }, APP_TITLE),
        h("div", { className: "zy-topbar-sub" }, APP_SUBTITLE)
      ),
      h(antd.Tag, { color: props.source === "模拟" ? "purple" : "green", style: { margin: 0 } }, props.source + "数据"),
      h(antd.Button, { size: "small", icon: h(RefreshIcon), onClick: props.onRefresh }, "刷新"),
      h(antd.Button, { size: "small", type: "primary", onClick: props.onAgent }, h(SparkIcon), " 问 Agent")
    );
  }

  function ModuleNav(props) {
    return h("div", { className: "zy-rail" },
      h("div", { className: "zy-rail-label" }, "功能模块"),
      props.modules.map(function (mod) {
        var active = mod.key === props.active;
        return h("div", { key: mod.key, className: "zy-nav-item" + (active ? " zy-active" : ""), onClick: function () { props.onSelect(mod.key); } },
          h("div", { className: "zy-nav-ico" }, mod.icon),
          h("div", { style: { minWidth: 0 } },
            h("div", { className: "zy-nav-name" }, mod.label),
            h("div", { className: "zy-nav-desc" }, mod.short)
          )
        );
      })
    );
  }

  function KpiStrip(props) {
    return h("div", { className: "zy-kpis" },
      (props.items || []).map(function (item) {
        return h("div", { key: item.label, style: { background: T.panel, border: "1px solid " + T.border, borderRadius: 9, padding: "12px 14px", boxShadow: T.shadow } },
          h("div", { style: { fontSize: 11, color: T.faint, fontWeight: 600 } }, item.label),
          h("div", { style: { fontSize: 24, fontWeight: 700, color: item.color || T.text, marginTop: 4, lineHeight: 1.2 } }, item.value)
        );
      })
    );
  }

  function EmptyState(props) {
    return h("div", { style: { textAlign: "center", padding: "52px 20px", color: T.sub } },
      h("div", { style: { fontSize: 40, marginBottom: 12 } }, props.icon),
      h("div", { style: { fontWeight: 650, color: T.text } }, props.title),
      h("div", { style: { fontSize: 12, marginTop: 8, lineHeight: 1.6 } }, props.desc)
    );
  }

  function ReviewBar(props) {
    var tone = statusTone(props.status);
    return h("div", { style: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, marginTop: 16, padding: 12, background: T.inset, border: "1px solid " + T.border, borderRadius: 9 } },
      h(antd.Tag, { color: tone.color, style: { margin: 0 } }, tone.text),
      h("span", { style: { fontSize: 12, color: T.sub } }, "Trace " + props.traceId),
      h(antd.Input, { size: "small", value: props.reviewer, onChange: function (e) { props.setReviewer(e.target.value); }, placeholder: "具名审阅人（必填）", style: { width: 160 } }),
      h(antd.Button, { size: "small", type: "primary", disabled: !props.reviewer.trim() || props.status === "accepted", onClick: function () { props.onDecide("accept"); } }, "接受"),
      h(antd.Button, { size: "small", danger: true, disabled: !props.reviewer.trim() || props.status === "rejected", onClick: function () { props.onDecide("reject"); } }, "驳回"),
      h(antd.Button, { size: "small", disabled: props.status !== "accepted", onClick: props.onExport }, "导出"),
      h(antd.Button, { size: "small", onClick: props.onHandoff }, "交给 Agent")
    );
  }

  function InputText(props) {
    return h("div", null,
      h(antd.Input.TextArea, { className: "zy-textarea", value: props.value, rows: props.rows || 7, placeholder: props.placeholder, onChange: function (e) { props.onChange(e.target.value); } }),
      h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginTop: 10 } },
        h("span", { style: { fontSize: 11, color: T.faint } }, "输入真实咨询/业务文本，首次使用可载入示例"),
        h(antd.Button, { size: "small", type: "dashed", onClick: function () { props.onChange(props.example); } }, "载入示例文本")
      ),
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 10 } }, props.hint) : null
    );
  }

  function cellEditor(col, row, index, onCell) {
    var key = col.key;
    var val = row ? row[key] : undefined;
    function set(v) { onCell(index, key, v); }
    if (col.type === "number") {
      return h(antd.InputNumber, { size: "small", value: val === "" || val == null ? undefined : Number(val), min: col.min, max: col.max, step: col.step, style: { width: "100%" }, placeholder: col.placeholder, onChange: function (v) { set(v == null ? "" : v); } });
    }
    if (col.type === "select") {
      return h(antd.Select, { size: "small", value: val, style: { width: "100%" }, placeholder: col.placeholder, options: col.options, onChange: set });
    }
    if (col.type === "tags") {
      return h(antd.Select, { mode: "tags", size: "small", value: val || [], style: { width: "100%" }, placeholder: col.placeholder, options: col.options || [], onChange: set, tokenSeparators: ["，", ",", ";"] });
    }
    return h(antd.Input, { size: "small", value: val, placeholder: col.placeholder, onChange: function (e) { set(e.target.value); } });
  }

  function EditableTable(props) {
    var cols = props.columns;
    var importedState = useState(null), imported = importedState[0], setImported = importedState[1];
    var value = props.value || [];
    var rows = withRid(value);
    function importFile(file) {
      var form = new FormData();
      form.append("file", file);
      Q.host.fetch(IMPORT_ENDPOINT, { method: "POST", body: form }).then(function (response) {
        return response.json().then(function (data) {
          if (!response.ok) throw new Error(data.detail || ("HTTP " + response.status));
          return data;
        });
      }).then(function (parsed) {
        var result = rowsFromParsed(parsed, cols);
        if (!result.matched.length) {
          antd.message.error("未匹配到任何列。文件表头：" + ((parsed.headers || []).join("、") || "（空）") + "；本表需要：" + cols.map(function (c) { return c.label; }).join("、"));
          return;
        }
        var rowsToLoad = result.rows.slice(0, IMPORT_MAX_ROWS);
        setImported({ filename: parsed.filename || file.name, count: rowsToLoad.length });
        props.onChange(rowsToLoad.map(function (row) { var copy = Object.assign({}, row); copy.__rid = nextRid(); return copy; }));
        var missingRequired = cols.filter(function (c) { return c.required && result.matched.indexOf(c.key) === -1; }).map(function (c) { return c.label; });
        antd.message.success("已导入 " + rowsToLoad.length + " 行（匹配列 " + result.matched.length + "/" + cols.length + (result.rows.length > IMPORT_MAX_ROWS ? "，超出 " + IMPORT_MAX_ROWS + " 行已截断" : "") + "）" + (missingRequired.length ? "；未匹配必填列：" + missingRequired.join("、") : ""));
      }).catch(function (error) {
        antd.message.error("导入失败：" + (error.message || "无法解析文件，仅支持 .xlsx / .csv"));
      });
      return false;
    }
    function downloadTemplate() {
      function csvCell(value) {
        var text = String(value == null ? "" : value);
        return /[",\n]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text;
      }
      var header = cols.map(function (c) { return csvCell(c.label); }).join(",");
      var example = cols.map(function (c) { return csvCell(c.type === "number" ? (c.placeholder || 1) : (c.placeholder || "")); }).join(",");
      var note = cols.map(function (c) { return csvCell(c.required ? "必填" : "可空"); }).join(",");
      var blob = new Blob(["\ufeff" + header + "\n" + example + "\n" + note + "\n"], { type: "text/csv;charset=utf-8" });
      var link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = (props.templateName || "导入模板") + ".csv";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    }
    function change(index, key, v) {
      var next = rows.map(function (r, i) { return i === index ? Object.assign({}, r, (function () { var o = {}; o[key] = v; return o; })()) : r; });
      props.onChange(next);
    }
    function addRow() {
      var blank = {};
      cols.forEach(function (c) { blank[c.key] = c.defaultValue !== undefined ? c.defaultValue : (c.type === "tags" ? [] : (c.type === "select" && c.options && c.options.length ? c.options[0].value : "")); });
      blank.__rid = nextRid();
      props.onChange(value.concat([blank]));
    }
    function removeRow(index) { props.onChange(value.filter(function (_, i) { return i !== index; })); }
    function loadSample() { props.onChange(withRid(clone(props.sample))); }
    var tableCols = cols.map(function (col) {
      return {
        title: col.label + (col.required ? " *" : ""), dataIndex: col.key, key: col.key, width: col.width, ellipsis: false,
        render: function (text, row, index) { return cellEditor(col, row, index, change); }
      };
    }).concat([{ title: "", key: "_op", width: 42, render: function (_, row, index) { return h(antd.Button, { size: "small", type: "text", danger: true, onClick: function () { removeRow(index); } }, "✕"); } }]);
    return h("div", null,
      h("div", { style: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 12, alignItems: "center" } },
        h(antd.Button, { size: "small", type: "primary", onClick: loadSample }, "一键导入示例数据"),
        h(antd.Upload, { accept: ".xlsx,.csv", showUploadList: false, beforeUpload: importFile },
          h(antd.Button, { size: "small" }, "导入 Excel/CSV")
        ),
        h(antd.Button, { size: "small", onClick: downloadTemplate }, "下载导入模板"),
        h(antd.Button, { size: "small", onClick: addRow }, "添加一行"),
        h(antd.Button, { size: "small", danger: true, onClick: function () { props.onChange([]); setImported(null); } }, "清空"),
        imported ? h(antd.Tag, { color: "green", style: { margin: 0 } }, "已导入 " + imported.filename + " · " + imported.count + " 行（可在表格中修改）") : null,
        h("span", { style: { fontSize: 11, color: T.faint } }, "支持从 Excel/CSV 导入，表头按列名自动匹配")
      ),
      h(antd.Table, { size: "small", rowKey: function (row) { return row && row.__rid ? row.__rid : "r" + Math.random(); }, pagination: false, dataSource: rows, columns: tableCols, className: "zy-cellgap", scroll: { x: Math.max(600, cols.length * 150) } }),
      value.length === 0 ? h(EmptyState, { icon: props.icon || "📄", title: "暂无数据", desc: "点击「导入 Excel/CSV」上传真实数据，或载入示例数据、逐行录入。" }) : null,
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 12 } }, props.hint) : null
    );
  }

  function editorFor(field, value, setField) {
    if (field.type === "subtable") {
      return h(EditableTable, { icon: field.icon || "🧩", columns: field.columns, value: value || [], onChange: setField, sample: field.sample, hint: field.hint, templateName: field.label });
    }
    if (field.type === "textarea") {
      return h(antd.Input.TextArea, { size: "small", value: value, rows: field.rows || 4, placeholder: field.placeholder, onChange: function (e) { setField(e.target.value); } });
    }
    if (field.type === "number") {
      return h(antd.InputNumber, { value: value === "" || value == null ? undefined : Number(value), min: field.min, max: field.max, step: field.step, style: { width: "100%" }, placeholder: field.placeholder, onChange: function (v) { setField(v == null ? "" : v); } });
    }
    if (field.type === "select") {
      return h(antd.Select, { value: value, options: field.options, placeholder: field.placeholder, onChange: setField });
    }
    if (field.type === "percent") {
      return h(antd.InputNumber, { value: value === "" || value == null ? undefined : Number(value), min: field.min < 0 ? field.min : 0, max: field.max, step: field.step || 0.01, style: { width: "100%" }, addonAfter: "%", placeholder: field.placeholder, onChange: function (v) { setField(v == null ? "" : v); } });
    }
    return h(antd.Input, { value: value, placeholder: field.placeholder, onChange: function (e) { setField(e.target.value); } });
  }

  function FormEditor(props) {
    var value = props.value || {};
    function setField(key, v) { var next = Object.assign({}, value); next[key] = v; props.onChange(next); }
    function loadSample() { props.onChange(clone(props.sample)); }
    return h("div", null,
      h("div", { style: { display: "flex", gap: 8, marginBottom: 12 } },
        h(antd.Button, { size: "small", type: "primary", onClick: loadSample }, "一键填入示例数据"),
        h(antd.Button, { size: "small", danger: true, onClick: function () { props.onChange({}); } }, "清空")
      ),
      props.fields.map(function (field) {
        if (field.type === "subtable") {
          return h("div", { key: field.key, style: { marginBottom: 14 } },
            h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label + (field.required ? " *" : "")),
            editorFor(field, value[field.key], function (v) { setField(field.key, v); })
          );
        }
        return h("div", { key: field.key, style: { marginBottom: 14 } },
          h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label + (field.required ? " *" : "")),
          editorFor(field, value[field.key], function (v) { setField(field.key, v); })
        );
      }),
      props.hint ? h("div", { className: "zy-hint", style: { marginTop: 10 } }, props.hint) : null
    );
  }

  function ExtraInput(props) {
    var fields = props.fields || [];
    if (!fields.length) return null;
    return h("div", { style: { marginBottom: 12 } },
      fields.map(function (field) {
        return h("div", { key: field.key, style: { marginBottom: 10 } },
          h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, field.label),
          h(antd.Input, { size: "small", value: field.value, placeholder: field.placeholder, onChange: function (e) { field.onChange(e.target.value); } })
        );
      })
    );
  }

  function AgentDock(props) {
    var listRef = useRef(null);
    useEffect(function () {
      if (listRef.current) listRef.current.scrollTop = listRef.current.scrollHeight;
    }, [props.messages]);
    if (!props.open) return null;
    return h("div", null,
      h("div", { className: "zy-mask", onClick: props.onClose }),
      h("div", { className: "zy-dock" },
        h("div", { className: "zy-chat" },
          h("div", { className: "zy-chat-head" },
            h("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 } },
              h("span", { style: { fontWeight: 650, fontSize: 15, color: T.text } }, "智能体助手 · " + (props.moduleLabel || "")),
              h("button", { "aria-label": "关闭", onClick: props.onClose, style: { border: "none", background: "transparent", cursor: "pointer", fontSize: 18, lineHeight: 1, color: T.sub, padding: "4px 8px", borderRadius: 6 } }, "✕")
            ),
            h("div", { className: "zy-tagline", style: { marginTop: 8 } }, "直接打字告诉我你要做什么，我会自动载入示例数据并运行对应模块。"),
            h("div", { className: "zy-chips", style: { marginTop: 10 } },
              props.modules.map(function (mod) {
                return h("span", { key: mod.key, className: "zy-chip", onClick: function () { props.onCommand(mod.key, mod.chipLabel); } }, mod.chipLabel || ("运行「" + mod.label + "」"));
              })
            )
          ),
          h("div", { className: "zy-chat-list", ref: listRef },
            (props.messages || []).map(function (msg, i) {
              return h("div", { key: i, className: "zy-msg " + (msg.role === "user" ? "zy-msg-user" : "zy-msg-bot") },
                h("div", { className: "zy-msg-bubble" }, msg.text),
                msg.card ? h("div", { className: "zy-msg-card" }, msg.card) : null
              );
            })
          ),
          h("div", { className: "zy-chat-input" },
            h(antd.Input, { value: props.draft, placeholder: "例如：帮我评估这3家供应商 / 计算补货量 / 监控风险", onChange: function (e) { props.setDraft(e.target.value); }, onPressEnter: function (e) { if (props.draft.trim()) { props.onSend(props.draft); e.preventDefault(); } } }),
            h(antd.Button, { type: "primary", style: { marginTop: 10, width: "100%" }, loading: props.busy, onClick: function () { if (props.draft.trim()) props.onSend(props.draft); } }, "发送")
          )
        )
      )
    );
  }

  function PeopleStudio() {
    var mods = [
  { key: "permission", inputKind: "table", icon: "🛡️", label: "权限建议", short: "角色矩阵 · 缺失/超配", chipLabel: "生成权限方案", featNo: 23, keywords: ["权限", "角色", "授权", "组织"],
    columns: [
      { key: "name", label: "姓名", required: true, width: 120, placeholder: "如：张工" },
      { key: "role", label: "角色", required: true, width: 130, type: "select", options: [{ value: "管理员", label: "管理员" }, { value: "部门经理", label: "部门经理" }, { value: "财务", label: "财务" }, { value: "销售", label: "销售" }, { value: "采购", label: "采购" }, { value: "员工", label: "员工" }], placeholder: "选择角色" },
      { key: "permissions", label: "当前权限", type: "tags", width: 260, placeholder: "输入权限，回车分隔", options: [{ value: "数据读写", label: "数据读写" }, { value: "用户管理", label: "用户管理" }, { value: "财务审批", label: "财务审批" }, { value: "系统配置", label: "系统配置" }, { value: "本部门审批", label: "本部门审批" }, { value: "报表查看", label: "报表查看" }] }
    ],
    sample: [
      { name: "张工", role: "管理员", permissions: ["数据读写", "用户管理", "财务审批", "系统配置"] },
      { name: "李工", role: "销售", permissions: ["客户查看", "订单查看", "业绩查看"] },
      { name: "王芳", role: "财务", permissions: ["财务审批", "报表查看", "数据读写"] }
    ],
    hint: "录入组织与用户真实权限，系统对照角色矩阵检查缺失与超配权限，并给出高危/关注/正常分级。",
    run: function (v) { return request(APP + "/artifacts/permission", { users: v }); },
    render: function (r) {
      var p = r.payload || {}; var rows = p.users || [];
      var high = rows.filter(function (x) { return x.rank === "高危"; }).length;
      var notice = rows.filter(function (x) { return x.rank === "关注"; }).length;
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "用户数", value: p.count, color: T.primary },
          { label: "高危", value: high, color: T.red },
          { label: "关注", value: notice, color: T.amber }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "权限风险明细", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: "name", pagination: false, dataSource: rows, scroll: { x: true }, columns: [
            { title: "姓名", dataIndex: "name" }, { title: "角色", dataIndex: "role" },
            { title: "缺失", dataIndex: "missing", render: function (v) { return (v || []).map(function (x, i) { return h(antd.Tag, { key: i, color: "red", style: { margin: 0 } }, x); }); } },
            { title: "超配", dataIndex: "excessive", render: function (v) { return (v || []).map(function (x, i) { return h(antd.Tag, { key: i, color: "orange", style: { margin: 0 } }, x); }); } },
            { title: "级别", dataIndex: "rank", render: function (v) { return h(antd.Tag, { color: v === "高危" ? "red" : v === "关注" ? "orange" : "green", style: { margin: 0 } }, v); } }
          ]})
        )
      );
    }
  },
  { key: "contact", inputKind: "table", icon: "📇", label: "通讯录协作", short: "全员检索 · 技能定位", chipLabel: "检索通讯录", featNo: 24, keywords: ["通讯录", "联系人", "检索", "找谁"],
    extraInputs: [{ key: "keyword", label: "检索关键词（可选）", placeholder: "按姓名/部门/职位/电话/技能检索，如：财务主管" }],
    columns: [
      { key: "name", label: "姓名", required: true, width: 110, placeholder: "如：王芳" },
      { key: "department", label: "部门", width: 120, placeholder: "如：财务部" },
      { key: "title", label: "职位", width: 120, placeholder: "如：财务主管" },
      { key: "phone", label: "电话", width: 140, placeholder: "如：13800001111" },
      { key: "email", label: "邮箱", width: 180, placeholder: "如：wangfang@zhiyun.cn" },
      { key: "skills", label: "技能", type: "tags", width: 210, placeholder: "输入技能，回车分隔" }
    ],
    sample: [
      { name: "王芳", department: "财务部", title: "财务主管", phone: "13800001111", email: "wangfang@zhiyun.cn", skills: ["预算", "报销审核"] },
      { name: "陈明", department: "研发部", title: "机械工程师", phone: "13800002222", email: "chenming@zhiyun.cn", skills: ["电机设计", "铸造工艺"] },
      { name: "赵敏", department: "质量部", title: "质量经理", phone: "13800003333", email: "zhaomin@zhiyun.cn", skills: ["来料检验", "质量体系"] }
    ],
    hint: "录入全员通讯录，系统按姓名/部门/职位/电话/技能做全文检索，便于跨部门协作找人。",
    run: function (v, extra) { return request(APP + "/artifacts/contact", { people: v, keyword: (extra && extra.keyword) || "" }); },
    render: function (r) {
      var p = r.payload || {}; var rows = p.contacts || [];
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "命中人数", value: p.count, color: T.primary },
          { label: "关键词", value: p.keyword || "全部", color: T.violet }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "通讯录结果", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: "name", pagination: false, dataSource: rows, scroll: { x: true }, columns: [
            { title: "姓名", dataIndex: "name" }, { title: "部门", dataIndex: "department" }, { title: "职位", dataIndex: "title" },
            { title: "电话", dataIndex: "phone" }, { title: "邮箱", dataIndex: "email" },
            { title: "技能", dataIndex: "skills", render: function (v) { return (v || []).map(function (x, i) { return h(antd.Tag, { key: i, style: { margin: 0 } }, x); }); } }
          ]})
        )
      );
    }
  },
  { key: "approval", inputKind: "form", icon: "✅", label: "审批路径", short: "按金额/部门/紧急度", chipLabel: "推荐审批", featNo: 26, keywords: ["审批", "路径", "签字", "流程"],
    fields: [
      { key: "requester", label: "发起人", required: true, placeholder: "如：张工" },
      { key: "department", label: "部门", required: true, placeholder: "如：采购部" },
      { key: "amount", label: "金额", type: "number", required: true, min: 0, step: 0.01, placeholder: "如：120000" },
      { key: "level", label: "紧急度", type: "select", options: [{ value: "普通", label: "普通" }, { value: "紧急", label: "紧急" }], placeholder: "选择紧急度" }
    ],
    sample: { requester: "张工", department: "采购部", amount: 120000, level: "普通" },
    hint: "填写真实审批请求，系统按金额与紧急度推荐审批链与最终审批人，并给出适用说明。",
    run: function (v) { return request(APP + "/artifacts/approval", { rule: v }); },
    render: function (r) {
      var p = r.payload || {};
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "金额", value: p.amount, color: T.primary },
          { label: "最终审批人", value: p.final_approver, color: T.violet },
          { label: "环节数", value: (p.path || []).length, color: T.amber }
        ]}),
        h(antd.Alert, { style: { marginTop: 12 }, type: "info", showIcon: true, message: "推荐理由：" + p.reason }),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "审批路径", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h("div", { style: { display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center" } },
            (p.path || []).map(function (node, i) {
              return h(Fragment, { key: i }, i > 0 ? h("span", { style: { color: T.faint } }, " → ") : null, h(antd.Tag, { color: "blue", style: { margin: 0 } }, node));
            })
          )
        )
      );
    }
  },
  { key: "anniversary", inputKind: "table", icon: "🎂", label: "员工关怀", short: "生日/司龄 · 30天提醒", chipLabel: "生成关怀", featNo: 27, keywords: ["关怀", "生日", "司龄", "纪念"],
    columns: [
      { key: "name", label: "姓名", required: true, width: 110, placeholder: "如：刘华" },
      { key: "birthday", label: "生日", required: true, width: 120, placeholder: "如：1990-08-30" },
      { key: "hire_date", label: "入职日期", required: true, width: 120, placeholder: "如：2020-03-15" },
      { key: "department", label: "部门", width: 120, placeholder: "如：生产部" }
    ],
    sample: [
      { name: "刘华", birthday: "1990-08-30", hire_date: "2020-03-15", department: "生产部" },
      { name: "赵敏", birthday: "1992-09-05", hire_date: "2019-08-20", department: "质量部" },
      { name: "钱进", birthday: "1988-08-27", hire_date: "2016-06-10", department: "采购部" }
    ],
    hint: "录入员工名单，系统按当天所在 30 天窗口找出临近生日与入职纪念日，便于提前准备关怀。",
    run: function (v) { return request(APP + "/artifacts/anniversary", { employees: v }); },
    render: function (r) {
      var p = r.payload || {}; var b = p.birthdays || []; var a = p.anniversaries || [];
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "临近生日", value: b.length, color: T.primary },
          { label: "司龄纪念", value: a.length, color: T.amber },
          { label: "窗口(天)", value: p.window_days, color: T.violet }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "30 天内关怀提醒", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: function (row, i) { return row.name + row.type + i; }, pagination: false, dataSource: b.concat(a), scroll: { x: true }, columns: [
            { title: "姓名", dataIndex: "name" }, { title: "类型", dataIndex: "type" },
            { title: "部门", dataIndex: "department" }, { title: "距今天数", dataIndex: "days_away" },
            { title: "说明", render: function (_, row) { return row.type === "司龄纪念" ? (row.years + " 周年") : "生日"; } }
          ]})
        )
      );
    }
  },
  { key: "hr", inputKind: "table", icon: "📈", label: "人力分析", short: "人数/缺编/离职率/招聘", chipLabel: "分析人力", featNo: 28, keywords: ["人力", "离职", "缺编", "招聘", "人数"],
    columns: [
      { key: "name", label: "姓名", required: true, width: 110, placeholder: "如：刘华" },
      { key: "department", label: "部门", required: true, width: 120, placeholder: "如：生产部" },
      { key: "hire_date", label: "入职日期", required: true, width: 120, placeholder: "如：2020-03-15" },
      { key: "planned_headcount", label: "编制人数", type: "number", width: 120, min: 0, step: 1, placeholder: "如：60" }
    ],
    extraTable: [
      { key: "departures", label: "离职记录", icon: "🚪", columns: [
        { key: "name", label: "姓名", width: 120, placeholder: "如：钱进" },
        { key: "department", label: "部门", width: 120, placeholder: "如：生产部" },
        { key: "departure_date", label: "离职日期", width: 120, placeholder: "如：2026-07-01" }
      ], sample: [
        { name: "钱进", department: "生产部", departure_date: "2026-07-01" },
        { name: "孙丽", department: "质量部", departure_date: "2026-08-10" }
      ], hint: "离职记录可选填；填了才计算近一年离职率。" }
    ],
    sample: [
      { name: "刘华", department: "生产部", hire_date: "2020-03-15", planned_headcount: 60 },
      { name: "赵敏", department: "质量部", hire_date: "2019-08-20", planned_headcount: 20 },
      { name: "钱进", department: "生产部", hire_date: "2018-05-12", planned_headcount: 60 }
    ],
    hint: "录入在职员工与（可选）离职记录，系统计算编制缺编、近一年离职率、近90天招聘/平均招聘周期与部门分布。",
    run: function (v, extra) { return request(APP + "/artifacts/hr", { employees: v, departures: (extra && extra.departures) || [] }); },
    render: function (r) {
      var p = r.payload || {}; var s = p.summary || {}; var deps = p.departments || {};
      return h(Fragment, null,
        KpiStrip({ items: [
          { label: "在编人数", value: s.headcount, color: T.primary },
          { label: "缺编", value: s.headcount_gap, color: s.headcount_gap > 0 ? T.red : T.green },
          { label: "离职率%", value: s.turnover_rate + "%", color: s.turnover_rate > 10 ? T.red : T.amber },
          { label: "近90天招聘", value: s.recent_hires, color: T.violet }
        ]}),
        h(antd.Card, { size: "small", style: { marginTop: 14 }, title: "部门分布", extra: h(antd.Tag, { color: "geekblue" }, p.method) },
          h(antd.Table, { size: "small", rowKey: function (row, i) { return row.department; }, pagination: false, dataSource: Object.keys(deps).map(function (k) { return { department: k, count: deps[k] }; }), columns: [
            { title: "部门", dataIndex: "department" }, { title: "人数", dataIndex: "count" }
          ]})
        )
      );
    }
  }
];

    var activeState = useState(mods[0].key);
    var active = activeState[0], setActive = activeState[1];
    var inputsState = useState({}), inputs = inputsState[0], setInputs = inputsState[1];
    var extrasState = useState({}), extras = extrasState[0], setExtras = extrasState[1];
    var resultsState = useState({}), results = resultsState[0], setResults = resultsState[1];
    var runningState = useState(null), running = runningState[0], setRunning = runningState[1];
    var reviewerState = useState(""), reviewer = reviewerState[0], setReviewer = reviewerState[1];
    var agentOpenState = useState(false), agentOpen = agentOpenState[0], setAgentOpen = agentOpenState[1];
    var draftState = useState(""), draft = draftState[0], setDraft = draftState[1];
    var messagesState = useState([]), messages = messagesState[0], setMessages = messagesState[1];
    var busyState = useState(false), busy = busyState[0], setBusy = busyState[1];
    var sourceState = useState("真实"), source = sourceState[0], setSource = sourceState[1];
    var message = antd.App.useApp().message;
    var activeMod = mods.find(function (m) { return m.key === active; });

    function setInput(key, value) { var next = Object.assign({}, inputs); next[key] = value; setInputs(next); }
    function setExtra(key, field, value) { var current = extras[key] || {}; var next = Object.assign({}, extras); var merged = Object.assign({}, current); merged[field] = value; next[key] = merged; setExtras(next); }
    function clearResult(key) { var next = Object.assign({}, results); delete next[key]; setResults(next); }

    function runModule(key, overrideValue) {
      var mod = mods.find(function (m) { return m.key === key; });
      var value = overrideValue !== undefined ? overrideValue : inputs[key];
      var extra = extras[key] || {};
      if (isBlank(value)) { message.warning("请先录入数据，或点击「一键导入示例数据」"); return Promise.reject(new Error("empty")); }
      setRunning(key);
      return Promise.resolve(mod.run(stripRid(value), stripRid(extra))).then(function (data) {
        var next = Object.assign({}, results); next[key] = data; setResults(next);
        message.success(mod.label + "：已生成待审阅工件");
        return data;
      }).catch(function (e) { message.error(e.message || "执行失败"); throw e; }).finally(function () { setRunning(null); });
    }

    function decide(key, action) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件"); return; }
      if (!reviewer.trim()) { message.warning("请输入具名审阅人"); return; }
      var review = mod.review ? mod.review(result, action, reviewer) : request(APP + "/artifacts/" + result.id + "/reviews", { action: action, reviewer: reviewer });
      Promise.resolve(review).then(function (data) {
        var next = Object.assign({}, results); next[key] = data; setResults(next);
        message.success(action === "accept" ? "工件已接受" : "工件已驳回");
      }).catch(function (e) { message.error(e.message); });
    }

    function exportArtifact(key) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件"); return; }
      if (mod.exportFn) { mod.exportFn(result); return; }
      if (result.status !== "accepted") { message.warning("工件需先被接受"); return; }
      window.open(APP + "/artifacts/" + result.id + "/export", "_blank");
    }

    function handoff(key) {
      var result = results[key];
      var mod = mods.find(function (m) { return m.key === key; });
      if (!result) { message.warning("请先生成工件再交给 Agent"); return; }
      pushAgentContext({ label: mod.label, app_id: ID, artifact_id: result.id || result.ticket_id, kind: key, summary: result, source_type: source === "模拟" ? "simulated" : "real" });
      message.success("已将「" + mod.label + "」结果加入 Agent 上下文");
    }

    function detectModule(text) {
      var t = text.toLowerCase();
      for (var i = 0; i < mods.length; i++) {
        var mod = mods[i];
        for (var j = 0; j < (mod.keywords || []).length; j++) {
          if (t.indexOf(mod.keywords[j]) >= 0) return mod.key;
        }
      }
      return mods[0].key;
    }

    function artifactCard(key, data) {
      var mod = mods.find(function (m) { return m.key === key; });
      var status = data.status || "pending_review";
      return h("div", null,
        h("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 } },
          h("strong", { style: { fontSize: 12.5 } }, mod.label),
          h(antd.Tag, { color: statusTone(status).color, style: { margin: 0 } }, statusTone(status).text)
        ),
        h("div", { className: "zy-tagline" }, "工件已生成：" + (data.id || data.ticket_id || "")),
        h("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
          h(antd.Button, { size: "small", type: "primary", onClick: function () { setActive(key); setAgentOpen(false); } }, "查看结果"),
          h(antd.Button, { size: "small", onClick: function () { handoff(key); } }, "交给 Agent")
        )
      );
    }

    function agentCommand(key, prompt) {
      var mod = mods.find(function (m) { return m.key === key; });
      setMessages(function (prev) { return prev.concat([{ role: "user", text: prompt || mod.label }]); });
      setBusy(true); setActive(key);
      if (isBlank(inputs[key])) {
        setInput(key, clone(sampleFor(mod)));
        message.info("已载入示例数据，可替换为真实业务数据");
      }
      setTimeout(function () {
        runModule(key, sampleFor(mod)).then(function (data) {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: mod.label + "：已生成可审阅工件，请切换回界面确认结果。", card: artifactCard(key, data) }]); });
        }).catch(function () {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "执行失败，请检查输入后重试。" }]); });
        }).finally(function () { setBusy(false); });
      }, 300);
    }

    function agentSend(text) {
      setMessages(function (prev) { return prev.concat([{ role: "user", text: text }]); });
      setBusy(true);
      var key = detectModule(text);
      var mod = mods.find(function (m) { return m.key === key; });
      setActive(key);
      if (isBlank(inputs[key])) { setInput(key, clone(sampleFor(mod))); message.info("已载入示例数据，可替换为真实业务数据"); }
      setTimeout(function () {
        runModule(key, sampleFor(mod)).then(function (data) {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "已为你执行「" + mod.label + "」，下方是结果摘要，可回界面审阅与导出。", card: artifactCard(key, data) }]); });
        }).catch(function () {
          setMessages(function (prev) { return prev.concat([{ role: "bot", text: "执行「" + mod.label + "」出现问题，请检查输入后重试。" }]); });
        }).finally(function () { setBusy(false); });
      }, 300);
    }

    function renderInput(mod) {
      if (mod.inputKind === "text") {
        return h(InputText, { value: inputs[mod.key], example: mod.example, placeholder: mod.placeholder, rows: mod.rows, hint: mod.hint, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } });
      }
      if (mod.inputKind === "form") {
        return h(FormEditor, { fields: mod.fields, value: inputs[mod.key], sample: mod.sample, hint: mod.hint, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } });
      }
      return h("div", null,
        h(ExtraInput, { fields: (mod.extraInputs || []).map(function (f) { return { key: f.key, label: f.label, placeholder: f.placeholder, value: (extras[mod.key] || {})[f.key], onChange: function (v) { setExtra(mod.key, f.key, v); setSource("真实"); } }; }) }),
        h(EditableTable, { icon: mod.icon, columns: mod.columns, value: inputs[mod.key], sample: mod.sample, hint: mod.hint, templateName: mod.label, onChange: function (v) { setInput(mod.key, v); setSource("真实"); } }),
        (mod.extraTable || []).map(function (t) {
          return h("div", { key: t.key, style: { marginTop: 14 } },
            h("div", { style: { fontSize: 12, fontWeight: 650, color: T.text, marginBottom: 6 } }, t.label + "（可选）"),
            h(EditableTable, { icon: t.icon, columns: t.columns, value: (extras[mod.key] || {})[t.key], sample: t.sample, hint: t.hint, templateName: mod.label + "-" + t.label, onChange: function (v) { setExtra(mod.key, t.key, v); setSource("真实"); } })
          );
        })
      );
    }

    function renderResult(mod) {
      var result = results[mod.key];
      var isRunning = running === mod.key;
      if (isRunning) {
        return h("div", { style: { padding: "42px 0", textAlign: "center" } },
          h(antd.Spin, { tip: "智能引擎分析中…" }),
          h("div", { style: { fontSize: 12, color: T.sub, marginTop: 10 } }, "正在结合模型计算并生成可审阅结果")
        );
      }
      if (!result) {
        return h(EmptyState, { icon: mod.icon, title: "暂无分析结果", desc: "在左侧填入真实数据后点击「" + (mod.chipLabel || "开始分析") + "」，系统会生成带证据的可审阅工件。" });
      }
      var reviewable = mod.reviewable !== false;
      return h(Fragment, null,
        mod.render(result),
        h("div", { style: { display: "flex", alignItems: "center", gap: 8, marginTop: 14, fontSize: 12, color: T.sub } },
          h("span", { className: "zy-status-dot", style: { background: T.green } }),
          "数据来源：" + source + "，基于真实业务输入生成，模拟数据已明确标注。"
        ),
        reviewable ? h(ReviewBar, { status: result.status, traceId: result.id, reviewer: reviewer, setReviewer: setReviewer, onDecide: function (a) { decide(mod.key, a); }, onExport: function () { exportArtifact(mod.key); }, onHandoff: function () { handoff(mod.key); } })
          : h("div", { style: { marginTop: 14 } }, h(antd.Button, { size: "small", onClick: function () { handoff(mod.key); } }, "交给 Agent"))
      );
    }

    return h("div", { className: "zy-app" },
      h(AppHeader, { source: source, refreshing: false, onRefresh: function () { setSource("真实"); message.success("已刷新最新数据"); }, onAgent: function () { setAgentOpen(true); } }),
      h("div", { className: "zy-body" },
        h(ModuleNav, { modules: mods, active: active, onSelect: function (key) { setActive(key); } }),
        h("div", { className: "zy-main" },
          h("div", { key: active, className: "zy-fade" }, activeMod ? h("div", { className: "zy-cols" },
            h("div", { className: "zy-panel" },
              h("div", { className: "zy-panel-head" },
                h("div", null, h("div", { className: "zy-panel-title" }, activeMod.label), h("div", { className: "zy-panel-sub" }, activeMod.short)),
                h(antd.Tag, { color: "blue", style: { margin: 0 } }, "功能 " + activeMod.featNo)
              ),
              h("div", { className: "zy-panel-body" },
                renderInput(activeMod),
                h("div", { style: { display: "flex", gap: 8, marginTop: 14 } },
                  h(antd.Button, { className: "zy-run", type: "primary", size: "large", loading: running === activeMod.key, onClick: function () { runModule(activeMod.key); } }, activeMod.chipLabel || "开始分析"),
                  h(antd.Button, { size: "large", onClick: function () { setInput(activeMod.key, null); clearResult(activeMod.key); setSource("真实"); } }, "清空")
                )
              )
            ),
            h("div", { className: "zy-panel" },
              h("div", { className: "zy-panel-head" },
                h("div", null, h("div", { className: "zy-panel-title" }, "分析结果"), h("div", { className: "zy-panel-sub" }, "结果可审阅、导出或交给 Agent")),
                h(antd.Tag, { color: source === "模拟" ? "purple" : "blue", style: { margin: 0 } }, source + "数据")
              ),
              h("div", { className: "zy-panel-body" }, renderResult(activeMod))
            )
          ) : null)
        )
      ),
      h(AgentDock, { open: agentOpen, onClose: function () { setAgentOpen(false); }, modules: mods, moduleLabel: activeMod ? activeMod.label : "", messages: messages, draft: draft, setDraft: setDraft, busy: busy, onSend: agentSend, onCommand: agentCommand })
    );
  }

  Q.registerRoutes(ID, [{ path: "/apps/" + ID, component: PeopleStudio, label: APP_TITLE, icon: "🧑‍🤝‍🧑", priority: 79 }]);
})();
